### ISSUE TITLE
Restore(maimodorun) button does not respond well

### ISSUE THREAD

**Issue by rkonno** [ofuton/maimodorun#10]
RTE のメニュー部の復元（maimodorun）ボタンが、クリックする箇所によって反応しないことがある。

## Context

- スレッド機能のページのRTEの復元(maimodorun)ボタンに不具合がある
- 主に maimodorun アイコン以外の領域が反応しないことが多い
- おそらくアイコン自体にイベントリスナーが付与されているため

## Process

以下に再現の手順を記す。

1. スレッドページにてRTEを開く
2. メニュー部の復元(maimodorun)ボタンのアイコン部分以外の領域をクリックする

## Expected result

- 復元(maimodorun)ボタンを押すことで、問題なく復元できる

## Current result

- 復元(maimodorun)ボタンを押しても反応がないことがある

## `restore button does not respond well...` screenshot

[![Image from Gyazo](https://i.gyazo.com/107d93abe2cc393658dc82d01d298525.gif)](https://gyazo.com/107d93abe2cc393658dc82d01d298525)

**Comment by emiksk** [comment]
Closed by #36
