### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rkonno** [ofuton/maimodorun#22]
README.mdの情報が ver1.1.0 に対応していないので、更新する

## Context

とくになし

## Process

1. マークダウンにコンバート
1. 全体的に ver1.1.0 の情報に更新
1. デモ用の gif も更新する

## Expected result

ver1.1.0 の情報が含まれた最新のREADME.mdに更新されている

## Current result

README.mdに更新していない情報が多数ある

## `name of issue` screenshot

とくになし

**Comment by emiksk** [comment]
Closed by #37
