### ISSUE TITLE
Migrate to ES6 with webpack

### ISSUE THREAD

**Issue by emiksk** [ofuton/maimodorun#23]
I wanna migrate maimodorun to ES6 with webpack, because ES6 let us use `import` / `export` in src.

## Context
We can gain the following advantages from this:
1. We can separate a large logics into proper modules.
2. We can lint source code easily.

## Process
1. Install webpack with npm.
2. Migrate library under vendors to node_modules.

I try to migrate!

**Comment by rkonno** [comment]
Good attempt! :+1:

**Comment by emiksk** [comment]
Congratulations :tada: !
