### ISSUE TITLE
Support people page to save and recovery text

### ISSUE THREAD

**Issue by emiksk** [ofuton/maimodorun#25]
ピープルでもフォームの保存と復元を行うようにしたい．

## Context

現在はスレッドのみの対応なので，新たに対応する箇所を増やしたい．

## Process

新機能のため省略

## Expected result

期待される機能一覧
- ピープルの投稿用と返信用の RTE に文章を入力すると自動保存が行われる．
- RTE のツールバーに表示される「まいもどるんボタン」をクリックするとフォームに文章が入る．
- ポップアップから保存されたフォーム情報をクリックすると，対応するピープルのフォームを開いて，フォームの中に文章を入れる．
- ポップアップでは，ピープルの情報だということをわかるように表示される．

## Current result

新機能のため省略

**Comment by rkonno** [comment]
Related PR merged!
