### ISSUE TITLE
Support record page in app to save and recovery text

### ISSUE THREAD

**Issue by emiksk** [ofuton/maimodorun#30]
アプリレコードのコメントでもフォームの保存と復元を行うようにしたい．

## Context

アプリレコードのコメントもユーザに多用されており，テキストを保存，復元する機能の価値は高い．

## Process

新機能のため省略

## Expected result

期待される機能一覧
- アプリレコードのコメントの RTE に文章を入力すると自動保存が行われる．
- RTE のツールバーに表示される「まいもどるんボタン」をクリックするとフォームに文章が入る．
- ポップアップから保存されたフォーム情報をクリックすると，対応するアプリレコードのフォームを開いて，フォームの中に文章を入れる．
- ポップアップでは，アプリレコードの情報だということをわかるように表示される．

## Current result

新機能のため省略

**Comment by rkonno** [comment]
こちらPRマージ済みのため、クローズします！
