### ISSUE TITLE
Save text when you click cancel button in form

### ISSUE THREAD

**Issue by emiksk** [ofuton/maimodorun#38]
キャンセルボタンを押したときにテキストが保存されるようにしたい

## Context

送信ボタンが押された時はテキスト保存が実行されるが，キャンセルされた時は保存されておらず，保存されたテキストが最後の状態と乖離しているケースがある．
そこで，キャンセルボタンを押した時もテキストが保存されるようにしたい．

## Process

1. フォームにテキストを入力する
2. 自動保存が実行される前にキャンセルボタンを押す
3. まいもどるんボタンを押してテキストを復元する

## Expected result

1. で入力したテキストが復元できる

## Current result

1. で入力したテキストが復元できない．(そもそも以前保存されたテキストがない場合，まいもどるんボタンが出てない)

**Comment by rkonno** [comment]
Related PR Merged!
