### ISSUE TITLE
Adopt a system of linting utility for JavaScript 

### ISSUE THREAD

**Issue by rkonno** [ofuton/maimodorun#4]
JavaScript のための静的検証ツールを導入し、コードを実行する前に明らかなバグを見つけたり、括弧やスペースの使い方などのスタイルを統一したい。

とくにデファクトスタンダードとなりつつある [ESLint - Pluggable JavaScript linter](https://eslint.org/) を導入する。

## Context

- コードレビューによってスタイルの統一を目指してきたが、あきらかにコストであるため自動化したい
- JavaScript のコーディング規約としてのベストプラクティスに則っていきたい

## Process

当 issue はバグの改修や新規機能の追加などではないため当項目は省略します。

## Expected result

- `eslint` コマンドで自動的にLintチェックがされる
- 基本的なコーディングスタイルを気にせず、実装部分のコードレビューに集中できる

## Current result

- レビューによりコード品質を担保する
- ベストプラクティスに則ったコーディング規約は持っていない

## screenshot

とくにない

**Comment by emiksk** [comment]
やるじゃん
