### ISSUE TITLE
Save text when you submit text with keyboard

### ISSUE THREAD

**Issue by emiksk** [ofuton/maimodorun#40]
キーボードを利用して送信ボタンを押した時にもテキストが保存されるようにしたい．

## Context

キーボードを利用してテキストを送信することは多いが，現状 mousedown にしか対応していないので，不便．

## Process

1. フォームにテキストを入力する
2. 自動保存が実行される前に TAB -> Enter で送信する
3. まいもどるんボタンを押してテキストを復元する

## Expected result

1. で入力したテキストが復元される

## Current result

1. で入力したテキストが復元できない

**Comment by rkonno** [comment]
Related PR Merged!
