### ISSUE TITLE
Update ScreenShot for Chrome Web Store

### ISSUE THREAD

**Issue by rkonno** [ofuton/maimodorun#44]
ストア用のスクリーンショットを更新する。

## Context

スクリーンショット内の文章内に kintone のロゴが入っており、ガイドラインに抵触する可能性があるため

## Expected result

スクリーンショット内の文章内の kintone 表記はノーマルなテキストタイプに変更する

## Current result

スクリーンショット内の文章内に kintone のロゴが含まれている

**Comment by emiksk** [comment]
Closed by #45
