### ISSUE TITLE
Support replies in a thread

### ISSUE THREAD

**Issue by emiksk** [ofuton/maimodorun#6]
スレッドの返信もフォームの保存と復元を行うようにしたい．

## Context
現在はスレッドのコメントのみの対応なので，新たに対応する箇所を増やしたい．
スレッドのコメントはコメントと同様に長文を書き込むこともあり，利用頻度も多いので，対応する価値が高い．

## Process
新機能なので省略

## Expected result
期待される機能一覧
- スレッドの返信用の RTE に文章を入力すると自動保存が行われる．
- RTE のツールバーに表示される「まいもどるんボタン」をクリックするとフォームに文章が入る．
- ポップアップから保存されたフォーム情報をクリックすると，対応するスレッドのコメントの返信フォームを開いて，フォームの中に文章を入れる．
- ポップアップでは，スレッドのコメントなのか返信なのかをわかるように表示される．

## Current result
新機能なので省略

## `name of issue` screenshot
新機能なので省略

**Comment by rkonno** [comment]
#18 無事リリースされたのでクローズ
お疲れ様でした 😺
